spring.application.name=tts
spring.profiles.active=prod

tts.api-key=${GEMINI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/tts_db
spring.datasource.username=postgres
spring.datasource.password=postgres

aws.s3.region=${AWS_S3_REGION:ap-south-1}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.cdn.base-url=${AWS_CDN_BASE_URL}

app.static-content.generated-audio=file:./generated-audio