spring.application.name=tts
spring.profiles.active=local

app.tts-api-service.api-key=${GEMINI_API_KEY}
app.cors.allowed-origin-patters=${CORS_ALLOWED_ORIGIN_PATTERNS}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tts_db}?sslmode=${DB_SSL:disable}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

aws.s3.region=${AWS_S3_REGION:ap-south-1}
aws.s3.bucket=${AWS_S3_BUCKET}
aws.cdn.base-url=${AWS_CDN_BASE_URL}